apiVersion: v1
kind: Service
metadata:
  name: {{ include "dragonflydb.name" . }}
  labels:
    app: {{ include "dragonflydb.name" . }}
spec:
  type: NodePort
  ports:
    - port: 6379  # This is the port on which the service will be exposed
      targetPort: 6379  # This is the port inside the pod where the application is listening
      protocol: TCP
      name: redis
      nodePort: 30082  # NodePort for external access
  selector:
    app: {{ include "dragonflydb.name" . }}
