apiVersion: v1
kind: Service
metadata:
  name: {{ include "dragonflydb.name" . }}
  labels:
    app: {{ include "dragonflydb.name" . }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: {{ include "dragonflydb.name" . }}
